{% set name = "bigearthnet-encoder" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 472bf48414c3355c2fdd5cb017142f7b31d6951a53cf21478afda6e54f44943d

build:
  entry_points:
    - ben_encoder = bigearthnet_encoder.encoder:encoder_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<3.11
  run:
    - bigearthnet-common >=2,<3
    - bigearthnet-patch-interface >=0.1,<0.2
    - fastcore >=1.3.27,<2.0.0
    - python-lmdb >=1.3.0,<2.0.0
    - numpy >=1.19,<2.0
    - pandas >=1.3.5,<2.0.0
    - pydantic >=1.9.0,<2.0.0
    - python >=3.6,<3.11
    - rasterio >=1.2.10,<2.0.0
    - rich >=10,<14
    - rich-click >=1.3.2,<2.0.0

test:
  imports:
    - bigearthnet_encoder
  commands:
    - pip check
    - ben_encoder --help
  requires:
    - pip

about:
  home: https://github.com/kai-tub/bigearthnet_encoder/
  summary: A flexible BigEarthNet encoder that allows one to quickly convert BigEarthNet to a DL-optimization data format.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
